// Code generated by mockery. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/hotelapp/booking-service/internal/domain"
	"github.com/stretchr/testify/mock"
)

type BookingRepository struct{ mock.Mock }

func (m *BookingRepository) Create(ctx context.Context, b *domain.Booking) error {
	args := m.Called(ctx, b)
	return args.Error(0)
}
func (m *BookingRepository) GetByID(ctx context.Context, id string) (*domain.Booking, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil { return nil, args.Error(1) }
	return args.Get(0).(*domain.Booking), args.Error(1)
}
func (m *BookingRepository) GetAll(ctx context.Context) ([]*domain.Booking, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil { return nil, args.Error(1) }
	return args.Get(0).([]*domain.Booking), args.Error(1)
}
func (m *BookingRepository) GetByUserID(ctx context.Context, userID string) ([]*domain.Booking, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil { return nil, args.Error(1) }
	return args.Get(0).([]*domain.Booking), args.Error(1)
}
func (m *BookingRepository) Update(ctx context.Context, b *domain.Booking) error {
	args := m.Called(ctx, b)
	return args.Error(0)
}
func (m *BookingRepository) Delete(ctx context.Context, id string) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}
func (m *BookingRepository) ChangeStatus(ctx context.Context, id string, status domain.BookingStatus) error {
	args := m.Called(ctx, id, status)
	return args.Error(0)
}
