// Code generated by mockery. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/hotelapp/booking-service/internal/domain"
	"github.com/stretchr/testify/mock"
)

type RoomRepository struct{ mock.Mock }

func (m *RoomRepository) GetAll(ctx context.Context) ([]*domain.Room, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil { return nil, args.Error(1) }
	return args.Get(0).([]*domain.Room), args.Error(1)
}

func (m *RoomRepository) GetByID(ctx context.Context, id string) (*domain.Room, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil { return nil, args.Error(1) }
	return args.Get(0).(*domain.Room), args.Error(1)
}
